import {
  Tecnico,
  Provedor,
  OrdemServico,
  SLAPolicy,
  KPI,
  CalendarioEvento,
  CMDBItem,
  Credential,
  Mudanca,
  TimeEntry,
  Plantao,
} from '@/types';

export const MOCK_TECNICOS: Tecnico[] = [
  {
    id: '1',
    nome: 'Carlos Silva',
    especializacao: 'Suporte N2 / Campo',
    ordensAtivas: 3,
    taxaResolucao: 96,
    tempoMedio: 2.1,
    status: 'disponivel',
    grade: 'A',
    score: 94,
    email: 'carlos@ajust.com',
    telefone: '(81) 99999-0001',
  },
  {
    id: '2',
    nome: 'Fernanda Costa',
    especializacao: 'NOC / Análise',
    ordensAtivas: 2,
    taxaResolucao: 94,
    tempoMedio: 1.8,
    status: 'disponivel',
    grade: 'A',
    score: 91,
    email: 'fernanda@ajust.com',
    telefone: '(81) 99999-0002',
  },
  {
    id: '3',
    nome: 'Roberto Almeida',
    especializacao: 'Suporte Lógico',
    ordensAtivas: 5,
    taxaResolucao: 88,
    tempoMedio: 3.2,
    status: 'disponivel',
    grade: 'B',
    score: 82,
    email: 'roberto@ajust.com',
    telefone: '(81) 99999-0003',
  },
  {
    id: '4',
    nome: 'João Pereira',
    especializacao: 'Infraestrutura',
    ordensAtivas: 4,
    taxaResolucao: 72,
    tempoMedio: 5.1,
    status: 'disponivel',
    grade: 'C',
    score: 72,
    email: 'joao@ajust.com',
    telefone: '(81) 99999-0004',
  },
  {
    id: '5',
    nome: 'Lucas Mendes',
    especializacao: 'Implantação / Config',
    ordensAtivas: 1,
    taxaResolucao: 91,
    tempoMedio: 2.4,
    status: 'reuniao',
    grade: 'A',
    score: 91,
    email: 'lucas@ajust.com',
    telefone: '(81) 99999-0005',
  },
  {
    id: '6',
    nome: 'Ana Beatriz',
    especializacao: 'Redes / Segurança',
    ordensAtivas: 2,
    taxaResolucao: 98,
    tempoMedio: 1.5,
    status: 'disponivel',
    grade: 'A',
    score: 96,
    email: 'ana@ajust.com',
    telefone: '(81) 99999-0006',
  },
  {
    id: '7',
    nome: 'Marcos Vinicius',
    especializacao: 'Campo / Fibra',
    ordensAtivas: 6,
    taxaResolucao: 65,
    tempoMedio: 7.3,
    status: 'disponivel',
    grade: 'D',
    score: 62,
    email: 'marcos@ajust.com',
    telefone: '(81) 99999-0007',
  },
  {
    id: '8',
    nome: 'Paula Santos',
    especializacao: 'Monitoramento NOC',
    ordensAtivas: 0,
    taxaResolucao: 92,
    tempoMedio: 2.8,
    status: 'ferias',
    grade: 'A',
    score: 90,
    email: 'paula@ajust.com',
    telefone: '(81) 99999-0008',
  },
];

export const MOCK_PROVEDORES: Provedor[] = [
  {
    id: '1',
    nome: 'Meganet',
    cidade: 'Recife - PE',
    ordensAtivas: 12,
    slaCompliance: 96.2,
    status: 'ativo',
  },
  {
    id: '2',
    nome: 'UltraFibra',
    cidade: 'Caruaru - PE',
    ordensAtivas: 8,
    slaCompliance: 91.5,
    status: 'ativo',
  },
  {
    id: '3',
    nome: 'ConnectFibra',
    cidade: 'Campina Grande - PB',
    ordensAtivas: 5,
    slaCompliance: 88.0,
    status: 'ativo',
  },
  {
    id: '4',
    nome: 'NetBrasil',
    cidade: 'João Pessoa - PB',
    ordensAtivas: 3,
    slaCompliance: 100,
    status: 'ativo',
  },
  {
    id: '5',
    nome: 'FibraMax',
    cidade: 'Maceió - AL',
    ordensAtivas: 7,
    slaCompliance: 93.4,
    status: 'ativo',
  },
  {
    id: '6',
    nome: 'Rede10',
    cidade: 'Natal - RN',
    ordensAtivas: 2,
    slaCompliance: 97.8,
    status: 'ativo',
  },
  {
    id: '7',
    nome: 'InternetJá',
    cidade: 'Fortaleza - CE',
    ordensAtivas: 0,
    slaCompliance: 0,
    status: 'inativo',
  },
];

export const MOCK_ORDENS: OrdemServico[] = [
  {
    protocolo: '#0521',
    provedor: 'Meganet',
    tecnico: 'Carlos Silva',
    tecnicoId: '1',
    tipo: 'INCIDENTE_CRITICO',
    prioridade: 'CRITICA',
    status: 'EM_ANALISE',
    titulo: 'Falha de conectividade em ponto de distribuição',
    prazoSLA: new Date('2026-05-10T11:00:00'),
    criadaEm: new Date('2026-05-10T09:00:00'),
    slaStatus: 'risk',
    descricao:
      'Cliente reportou queda total em 3 concentrações. Análise inicial indica possível rompimento de backbone de fibra.',
  },
  {
    protocolo: '#0520',
    provedor: 'UltraFibra',
    tecnico: 'Fernanda Costa',
    tecnicoId: '2',
    tipo: 'DEGRADACAO_SERVICO',
    prioridade: 'ALTA',
    status: 'AG_CAMPO',
    titulo: 'Instabilidade reportada em região sul',
    prazoSLA: new Date('2026-05-10T13:00:00'),
    criadaEm: new Date('2026-05-10T08:45:00'),
    slaStatus: 'ok',
    descricao:
      'Latência intermitente afetando clientes da zona sul. Equipe de campo já mobilizada para verificação.',
  },
  {
    protocolo: '#0519',
    provedor: 'Meganet',
    tecnico: null,
    tecnicoId: null,
    tipo: 'CONSULTORIA_TECNICA',
    prioridade: 'NORMAL',
    status: 'ABERTA',
    titulo: 'Auditoria de topologia de rede',
    prazoSLA: new Date('2026-05-11T07:30:00'),
    criadaEm: new Date('2026-05-10T07:30:00'),
    slaStatus: 'ok',
    descricao: 'Auditoria completa da topologia atual e recomendações de melhoria.',
  },
  {
    protocolo: '#0518',
    provedor: 'ConnectFibra',
    tecnico: 'João Pereira',
    tecnicoId: '4',
    tipo: 'DEGRADACAO_SERVICO',
    prioridade: 'ALTA',
    status: 'EM_ANALISE',
    titulo: 'Análise de performance de backbone',
    prazoSLA: new Date('2026-05-10T10:00:00'),
    criadaEm: new Date('2026-05-10T06:00:00'),
    slaStatus: 'breach',
    descricao: 'Perda de pacotes de 15% no backbone. SLA quebrado - ação imediata necessária.',
  },
  {
    protocolo: '#0517',
    provedor: 'Meganet',
    tecnico: 'Roberto Almeida',
    tecnicoId: '3',
    tipo: 'IMPLANTACAO',
    prioridade: 'BAIXA',
    status: 'AG_TERCEIROS',
    titulo: 'Implantação de novo ponto de presença',
    prazoSLA: new Date('2026-05-12T08:00:00'),
    criadaEm: new Date('2026-05-10T08:00:00'),
    slaStatus: 'ok',
    descricao: 'Novo PoP em Olinda. Aguardando liberação do datacenter terceirizado.',
  },
  {
    protocolo: '#0516',
    provedor: 'UltraFibra',
    tecnico: 'Ana Beatriz',
    tecnicoId: '6',
    tipo: 'INCIDENTE_CRITICO',
    prioridade: 'CRITICA',
    status: 'EM_EXECUCAO',
    titulo: 'Ataque DDoS no gateway principal',
    prazoSLA: new Date('2026-05-10T14:00:00'),
    criadaEm: new Date('2026-05-10T10:30:00'),
    slaStatus: 'ok',
    descricao: 'Mitigação de DDoS em andamento. Filtros aplicados, tráfego normalizando.',
  },
  {
    protocolo: '#0515',
    provedor: 'NetBrasil',
    tecnico: 'Lucas Mendes',
    tecnicoId: '5',
    tipo: 'INTEGRACAO',
    prioridade: 'NORMAL',
    status: 'EM_EXECUCAO',
    titulo: 'Integração com sistema de billing',
    prazoSLA: new Date('2026-05-13T18:00:00'),
    criadaEm: new Date('2026-05-09T14:00:00'),
    slaStatus: 'ok',
    descricao: 'Integração do ERP do provedor com sistema de billing do provedor.',
  },
  {
    protocolo: '#0514',
    provedor: 'FibraMax',
    tecnico: 'Marcos Vinicius',
    tecnicoId: '7',
    tipo: 'TREINAMENTO',
    prioridade: 'BAIXA',
    status: 'AG_CAMPO',
    titulo: 'Capacitação equipe NOC',
    prazoSLA: new Date('2026-05-14T12:00:00'),
    criadaEm: new Date('2026-05-09T09:00:00'),
    slaStatus: 'ok',
    descricao: 'Treinamento da equipe de NOC do provedor em procedimentos de troubleshooting.',
  },
  {
    protocolo: '#0513',
    provedor: 'Meganet',
    tecnico: 'Carlos Silva',
    tecnicoId: '1',
    tipo: 'REVISAO_CONFIGURACAO',
    prioridade: 'NORMAL',
    status: 'RESOLVIDA',
    titulo: 'Revisão de config de roteadores core',
    prazoSLA: new Date('2026-05-09T18:00:00'),
    criadaEm: new Date('2026-05-08T10:00:00'),
    slaStatus: 'ok',
    descricao: 'Revisão concluída. Diversas melhorias de segurança implementadas.',
  },
  {
    protocolo: '#0512',
    provedor: 'Rede10',
    tecnico: 'Fernanda Costa',
    tecnicoId: '2',
    tipo: 'PLANEJAMENTO',
    prioridade: 'BAIXA',
    status: 'EM_ANALISE',
    titulo: 'Planejamento de expansão 2027',
    prazoSLA: new Date('2026-05-20T18:00:00'),
    criadaEm: new Date('2026-05-08T15:00:00'),
    slaStatus: 'ok',
    descricao: 'Projeto de expansão para 10 novas cidades em 2027.',
  },
  {
    protocolo: '#0511',
    provedor: 'ConnectFibra',
    tecnico: 'Roberto Almeida',
    tecnicoId: '3',
    tipo: 'CONSULTORIA_TECNICA',
    prioridade: 'ALTA',
    status: 'FECHADA',
    titulo: 'Diagnóstico de lentidão generalizada',
    prazoSLA: new Date('2026-05-09T12:00:00'),
    criadaEm: new Date('2026-05-07T08:00:00'),
    slaStatus: 'ok',
    descricao: 'Diagnóstico concluído. Gargalo identificado no concentrador PPPoE.',
  },
  {
    protocolo: '#0510',
    provedor: 'UltraFibra',
    tecnico: 'João Pereira',
    tecnicoId: '4',
    tipo: 'DEGRADACAO_SERVICO',
    prioridade: 'ALTA',
    status: 'CANCELADA',
    titulo: 'Queda intermitente zona norte',
    prazoSLA: new Date('2026-05-09T10:00:00'),
    criadaEm: new Date('2026-05-07T06:00:00'),
    slaStatus: 'ok',
    descricao: 'Cancelada - problema resolvido pelo próprio provedor.',
  },
];

export const MOCK_SLA_POLICIES: SLAPolicy[] = [
  {
    id: '1',
    prioridade: 'CRITICA',
    tipo: 'INCIDENTE_CRITICO',
    horas: 2,
    override: true,
    ativo: true,
  },
  { id: '2', prioridade: 'CRITICA', tipo: null, horas: 4, override: false, ativo: true },
  { id: '3', prioridade: 'ALTA', tipo: 'INCIDENTE_CRITICO', horas: 4, override: true, ativo: true },
  {
    id: '4',
    prioridade: 'ALTA',
    tipo: 'DEGRADACAO_SERVICO',
    horas: 8,
    override: true,
    ativo: true,
  },
  { id: '5', prioridade: 'NORMAL', tipo: null, horas: 24, override: false, ativo: true },
  { id: '6', prioridade: 'BAIXA', tipo: null, horas: 48, override: false, ativo: true },
];

export const MOCK_KPIS: KPI = {
  totalAbertas: 47,
  slaCompliance: 94.8,
  criticasAtivas: 3,
  tempoMedioResolucao: 6.2,
  taxaResolucao: 95.8,
  ordensAtrasadas: 4,
  ordensEmRisco: 2,
  provedoresAtivos: 6,
};

export const MOCK_EVENTOS: CalendarioEvento[] = [
  {
    id: '1',
    titulo: 'Reunião Semanal Meganet',
    tipo: 'REUNIAO',
    data: new Date('2026-05-11T10:00:00'),
    horaInicio: '10:00',
    horaFim: '11:00',
    descricao: 'Status report semanal com equipe Meganet',
  },
  {
    id: '2',
    titulo: 'Sprint Planning',
    tipo: 'REUNIAO_ONLINE',
    data: new Date('2026-05-11T14:00:00'),
    horaInicio: '14:00',
    horaFim: '15:30',
  },
  {
    id: '3',
    titulo: 'Agenda Carlos Silva',
    tipo: 'LEMBRETE',
    data: new Date('2026-05-10T08:00:00'),
    horaInicio: '08:00',
    horaFim: '20:00',
  },
  {
    id: '4',
    titulo: 'Agenda Fernanda Costa',
    tipo: 'LEMBRETE',
    data: new Date('2026-05-11T08:00:00'),
    horaInicio: '08:00',
    horaFim: '20:00',
  },
  { id: '5', titulo: 'Corpus Christi', tipo: 'FERIADO', data: new Date('2026-06-04T00:00:00') },
  {
    id: '6',
    titulo: 'Enviar relatório UltraFibra',
    tipo: 'LEMBRETE',
    data: new Date('2026-05-12T09:00:00'),
  },
  {
    id: '7',
    titulo: 'Revisão SLA ConnectFibra',
    tipo: 'REUNIAO',
    data: new Date('2026-05-13T15:00:00'),
    horaInicio: '15:00',
    horaFim: '16:00',
  },
  {
    id: '8',
    titulo: 'Agenda João Pereira',
    tipo: 'LEMBRETE',
    data: new Date('2026-05-12T08:00:00'),
    horaInicio: '08:00',
    horaFim: '20:00',
  },
];

export const MOCK_CMDB: CMDBItem[] = [
  {
    id: '1',
    provedor: 'Meganet',
    equipamento: 'OLT-Main-001',
    tipo: 'OLT',
    ambiente: 'Produção',
    ip: '10.10.1.1',
    status: 'Ativo',
  },
  {
    id: '2',
    provedor: 'Meganet',
    equipamento: 'Core-RTR-001',
    tipo: 'Roteador',
    ambiente: 'Produção',
    ip: '10.10.1.2',
    status: 'Ativo',
  },
  {
    id: '3',
    provedor: 'UltraFibra',
    equipamento: 'SW-Core-001',
    tipo: 'Switch',
    ambiente: 'Produção',
    ip: '192.168.1.1',
    status: 'Ativo',
  },
  {
    id: '4',
    provedor: 'ConnectFibra',
    equipamento: 'OLT-ZonaSul',
    tipo: 'OLT',
    ambiente: 'Produção',
    ip: '172.16.0.1',
    status: 'Manutenção',
  },
  {
    id: '5',
    provedor: 'NetBrasil',
    equipamento: 'FW-Perimeter',
    tipo: 'Firewall',
    ambiente: 'Produção',
    ip: '10.0.0.1',
    status: 'Ativo',
  },
  {
    id: '6',
    provedor: 'FibraMax',
    equipamento: 'RTR-Edge-01',
    tipo: 'Roteador',
    ambiente: 'Produção',
    ip: '10.20.1.1',
    status: 'Ativo',
  },
  {
    id: '7',
    provedor: 'Meganet',
    equipamento: 'SW-Access-05',
    tipo: 'Switch',
    ambiente: 'Produção',
    ip: '10.10.5.1',
    status: 'Erro',
  },
  {
    id: '8',
    provedor: 'Ajust-Lab',
    equipamento: 'Router-Test-02',
    tipo: 'Roteador',
    ambiente: 'Lab',
    ip: '192.168.100.1',
    status: 'Ativo',
  },
];

export const MOCK_CREDENTIALS: Credential[] = [
  {
    id: '1',
    provider: 'Meganet',
    equipment: 'OLT-Main-001',
    type: 'SSH',
    environment: 'Produção',
    username: 'admin',
    secret: '••••4321',
  },
  {
    id: '2',
    provider: 'Gateway Externo',
    equipment: 'API Gateway',
    type: 'API',
    environment: 'Produção',
    username: '—',
    secret: '••••key5',
  },
  {
    id: '3',
    provider: 'Lab-Local',
    equipment: 'Router-Test-02',
    type: 'Telnet',
    environment: 'Lab',
    username: 'root',
    secret: '••••rt9x',
  },
  {
    id: '4',
    provider: 'UltraFibra',
    equipment: 'SW-Core-001',
    type: 'SSH',
    environment: 'Produção',
    username: 'admin',
    secret: '••••8f2k',
  },
  {
    id: '5',
    provider: 'ConnectFibra',
    equipment: 'OLT-ZonaSul',
    type: 'SNMP',
    environment: 'Produção',
    username: 'monitor',
    secret: '••••snmp',
  },
  {
    id: '6',
    provider: 'AWS',
    equipment: 'Console Root',
    type: 'API',
    environment: 'Cloud',
    username: 'root@ajust.com',
    secret: '••••aws9',
  },
];

export const MOCK_MUDANCAS: Mudanca[] = [
  {
    id: 'CHG-001',
    titulo: 'Upgrade firmware OLT Meganet',
    tipo: 'Manutenção',
    status: 'APROVADO',
    prioridade: 'Alta',
    risco: 'Médio',
    solicitante: 'Carlos Silva',
    aprovador: 'Daniel Marques',
    plannedDate: '15 Mai 2026 02:00',
    windowStart: '02:00',
    windowEnd: '04:00',
    affectedSystems: ['OLT-Main-001', 'Rede Meganet Recife'],
    rollback: 'Restaurar backup de firmware anterior',
    description:
      'Atualização de firmware para versão 2.4.1 corrigindo vulnerabilidade de segurança',
    impact: 'Downtime estimado de 15-30 minutos durante a janela',
    data: new Date('2026-05-15T02:00:00'),
  },
  {
    id: 'CHG-002',
    titulo: 'Migração backbone UltraFibra',
    tipo: 'Migração',
    status: 'AGUARDANDO_APROVACAO',
    prioridade: 'Crítica',
    risco: 'Alto',
    solicitante: 'Fernanda Costa',
    aprovador: '—',
    plannedDate: '20 Mai 2026 00:00',
    windowStart: '00:00',
    windowEnd: '06:00',
    affectedSystems: ['Backbone UltraFibra', 'Core-Router-01', 'Core-Router-02'],
    rollback: 'Reativação do backbone antigo via script automatizado',
    description: 'Migração completa do backbone de 10G para 100G com novo hardware',
    impact: 'Downtime de até 4 horas para toda a rede UltraFibra',
    data: new Date('2026-05-20T00:00:00'),
  },
  {
    id: 'CHG-003',
    titulo: 'Adicionar VLAN ConnectFibra',
    tipo: 'Configuração',
    status: 'CONCLUIDO',
    prioridade: 'Média',
    risco: 'Baixo',
    solicitante: 'Roberto Almeida',
    aprovador: 'Daniel Marques',
    plannedDate: '08 Mai 2026 22:00',
    windowStart: '22:00',
    windowEnd: '23:00',
    affectedSystems: ['Switch-Core-001', 'Switch-Access-05'],
    rollback: 'Remover VLAN adicionada',
    description: 'Criação de VLAN 100 para segmentação de tráfego gerencial',
    impact: 'Sem impacto em produção',
    data: new Date('2026-05-08T22:00:00'),
  },
  {
    id: 'CHG-004',
    titulo: 'Troca de roteador core',
    tipo: 'Hardware',
    status: 'REJEITADO',
    prioridade: 'Alta',
    risco: 'Alto',
    solicitante: 'João Pereira',
    aprovador: 'Daniel Marques',
    plannedDate: '10 Mai 2026 08:00',
    windowStart: '08:00',
    windowEnd: '12:00',
    affectedSystems: ['Core-RTR-001', 'Toda rede'],
    rollback: 'Reinstalar roteador antigo',
    description: 'Substituição do roteador core por modelo de maior capacidade',
    impact: 'Downtime total durante a troca',
    data: new Date('2026-05-10T08:00:00'),
  },
  {
    id: 'CHG-005',
    titulo: 'Patch de segurança firewall',
    tipo: 'Software',
    status: 'EM_EXECUCAO',
    prioridade: 'Alta',
    risco: 'Médio',
    solicitante: 'Ana Beatriz',
    aprovador: 'Daniel Marques',
    plannedDate: '11 Mai 2026 01:00',
    windowStart: '01:00',
    windowEnd: '03:00',
    affectedSystems: ['FW-Perimeter'],
    rollback: 'Restaurar snapshot anterior do firewall',
    description: 'Aplicação de patch crítico de segurança CVE-2026-1234',
    impact: 'Possível reinicialização do firewall, failover automático para secundário',
    data: new Date('2026-05-11T01:00:00'),
  },
];

export const MOCK_TIME_ENTRIES: TimeEntry[] = [
  {
    id: '1',
    tecnico: 'Carlos Silva',
    os: '#0521',
    inicio: new Date('2026-05-10T09:00:00'),
    fim: new Date('2026-05-10T10:30:00'),
    duracao: 1.5,
    descricao: 'Análise inicial do rompimento',
  },
  {
    id: '2',
    tecnico: 'Fernanda Costa',
    os: '#0520',
    inicio: new Date('2026-05-10T08:45:00'),
    fim: null,
    duracao: 0.75,
    descricao: 'Diagnóstico de instabilidade',
  },
  {
    id: '3',
    tecnico: 'Roberto Almeida',
    os: '#0517',
    inicio: new Date('2026-05-10T08:00:00'),
    fim: new Date('2026-05-10T11:00:00'),
    duracao: 3.0,
    descricao: 'Preparação servidores PoP',
  },
  {
    id: '4',
    tecnico: 'Ana Beatriz',
    os: '#0516',
    inicio: new Date('2026-05-10T10:30:00'),
    fim: null,
    duracao: 0.5,
    descricao: 'Mitigação DDoS',
  },
  {
    id: '5',
    tecnico: 'Lucas Mendes',
    os: '#0515',
    inicio: new Date('2026-05-10T09:00:00'),
    fim: new Date('2026-05-10T16:00:00'),
    duracao: 7.0,
    descricao: 'Desenvolvimento API integração',
  },
];

export const MOCK_PLANTOES: Plantao[] = [
  {
    id: '1',
    tecnico: 'Carlos Silva',
    inicio: new Date('2026-05-10T08:00:00'),
    fim: new Date('2026-05-10T20:00:00'),
    tipo: 'Diurno',
  },
  {
    id: '2',
    tecnico: 'Fernanda Costa',
    inicio: new Date('2026-05-10T20:00:00'),
    fim: new Date('2026-05-11T08:00:00'),
    tipo: 'Noturno',
  },
  {
    id: '3',
    tecnico: 'Roberto Almeida',
    inicio: new Date('2026-05-11T08:00:00'),
    fim: new Date('2026-05-11T20:00:00'),
    tipo: 'Diurno',
  },
  {
    id: '4',
    tecnico: 'João Pereira',
    inicio: new Date('2026-05-11T20:00:00'),
    fim: new Date('2026-05-12T08:00:00'),
    tipo: 'Noturno',
  },
  {
    id: '5',
    tecnico: 'Carlos Silva',
    inicio: new Date('2026-05-12T08:00:00'),
    fim: new Date('2026-05-12T20:00:00'),
    tipo: 'Diurno',
  },
  {
    id: '6',
    tecnico: 'Fernanda Costa',
    inicio: new Date('2026-05-12T20:00:00'),
    fim: new Date('2026-05-13T08:00:00'),
    tipo: 'Noturno',
  },
];

export const CHART_DATA = [
  { day: '04 Mai', abertas: 8, fechadas: 6 },
  { day: '05 Mai', abertas: 12, fechadas: 9 },
  { day: '06 Mai', abertas: 6, fechadas: 10 },
  { day: '07 Mai', abertas: 10, fechadas: 8 },
  { day: '08 Mai', abertas: 14, fechadas: 11 },
  { day: '09 Mai', abertas: 9, fechadas: 12 },
  { day: '10 Mai', abertas: 7, fechadas: 5 },
];

export const SLA_DISTRIBUTION = [
  { name: 'No Prazo', value: 42, color: '#16a34a' },
  { name: 'Em Risco', value: 3, color: '#d97706' },
  { name: 'Quebrado', value: 2, color: '#dc2626' },
];

export const DISTRIBUICAO_TECNICOS = [
  { name: 'Carlos S.', ordens: 12 },
  { name: 'Fernanda C.', ordens: 9 },
  { name: 'Roberto A.', ordens: 7 },
  { name: 'João P.', ordens: 5 },
  { name: 'Ana B.', ordens: 8 },
  { name: 'Lucas M.', ordens: 4 },
  { name: 'Marcos V.', ordens: 2 },
];

export const TIPOS_SERVICO_DISPONIVEIS = [
  {
    id: '1',
    nome: 'Incidente Crítico',
    descricao: 'Falha grave — atendimento prioritário',
    slaDefault: '2h',
    ativo: true,
  },
  {
    id: '2',
    nome: 'Degradação de Serviço',
    descricao: 'Instabilidade a investigar',
    slaDefault: '8h',
    ativo: true,
  },
  {
    id: '3',
    nome: 'Consultoria Técnica',
    descricao: 'Análise, diagnóstico, auditoria',
    slaDefault: '24h',
    ativo: true,
  },
  {
    id: '4',
    nome: 'Implantação',
    descricao: 'Projeto de implantação/expansão',
    slaDefault: '48h',
    ativo: true,
  },
  {
    id: '5',
    nome: 'Treinamento',
    descricao: 'Capacitação da equipe do provedor',
    slaDefault: '48h',
    ativo: true,
  },
  {
    id: '6',
    nome: 'Revisão de Configuração',
    descricao: 'Revisão de setup/configuração existente',
    slaDefault: '24h',
    ativo: true,
  },
  {
    id: '7',
    nome: 'Planejamento',
    descricao: 'Projetos de capacidade e expansão',
    slaDefault: '72h',
    ativo: true,
  },
  {
    id: '8',
    nome: 'Integração',
    descricao: 'Integração com sistemas do provedor',
    slaDefault: '48h',
    ativo: true,
  },
];
